### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by fahadshamshad** [SunghwanHong/Deep-Matching-Prior#1]
Hi, nice work. When are you planning to release the code?

**Comment by SunghwanHong** [comment]
Hi,
I am planning to release the code as soon as I finish the works I'm currently working on (This should be done by end of this year). 
My initial plan was to release the code as soon as I got an accept, but then I had to do refactoring as it was not organized at all, and this is one of the reason prevented me from releasing the code. As I'm currently working on some of the projects including submission to CVPR and several personal projects, I have to say I won't be able to release the code now. However, I mostly borrowed code from GLU-Net, and in the paper, I included architectural designs in detail for reproduction, so it would provide sufficient intuition about how I implemented my work. 

Thanks for the inquiry, 
sunghwan Hong

**Comment by kampta** [comment]
Hi @SunghwanHong, thanks for the fantastic work!

Is there any update on the code release plan?
